In [1]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\Amin\Downloads\train.csv")
df.head(7)

   ID_code  target    var_0   var_1    var_2   var_3  ...  var_194  var_195  var_196  var_197  var_198  var_199
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  ...  18.5227  -2.3978   7.8784   8.5635  12.7803  -1.0914
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  ...  15.4305   2.0339   8.1267   8.7889  18.3560   1.9518
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  ...  21.6042   3.1417  -6.5213   8.2675  14.7222   0.3965
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  ...  23.0347  -1.2706  -2.9275  10.2922  17.9697  -8.9996
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  ...  13.2876  -1.5121   3.9267   9.5031  17.9974  -8.8104
5  train_5       0  11.4763 -2.3182  12.6080  8.6264  ...  14.9452   1.0314  -3.6241   9.7670  12.5809  -4.7602
6  train_6       0  11.8091 -0.0832   9.3494  4.2916  ...  18.3314   0.5845   9.1104   9.1143  10.8869  -3.2097

[7 rows x 202 columns]

In [2]:
#missing values per column
df.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
          ..
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

In [3]:
#missing values in the entire dataset
df.isnull().sum().sum()

np.int64(0)

In [5]:
#mean of each variable according to target 
df.groupby('target').mean(numeric_only=True)

            var_0     var_1      var_2     var_3      var_4  ...   var_195   var_196   var_197    var_198   var_199
target                                                       ...
0       10.626681 -1.695770  10.665876  6.788979  11.072412  ... -0.155601  2.260297  8.919032  15.924058 -3.415273
1       11.156418 -1.017613  11.156633  6.864113  11.131337  ... -0.021130  2.688583  8.810815  15.393283 -2.532243

[2 rows x 200 columns]

In [6]:
#count number of values for each target
df['target'].value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

In [7]:
df=df.drop(columns=['ID_code'])

In [8]:
df.describe()

              target          var_0          var_1  ...        var_197        var_198        var_199
count  200000.000000  200000.000000  200000.000000  ...  200000.000000  200000.000000  200000.000000
mean        0.100490      10.679914      -1.627622  ...       8.908158      15.870720      -3.326537
std         0.300653       3.040051       4.050044  ...       0.921625       3.010945      10.438015
min         0.000000       0.408400     -15.043400  ...       5.960600       6.299300     -38.852800
25%         0.000000       8.453850      -4.740025  ...       8.252800      13.829700     -11.208475
50%         0.000000      10.524750      -1.608050  ...       8.888200      15.934050      -2.819550
75%         0.000000      12.758200       1.358625  ...       9.593300      18.064725       4.836800
max         1.000000      20.315000      10.376800  ...      12.000400      26.079100      28.500700

[8 rows x 201 columns]

In [9]:
df.loc[:, 'var_0'].mean()

np.float64(10.679914252)

In [11]:
#filter var_0 variable from minimum to mean 
var_0_min=df['var_0'].min() 
var_0_mean=df['var_0'].mean() 

filtered_df=df[(df['var_0'] >= var_0_min) & (df['var_0'] <= var_0_mean)]
filtered_df

        target   var_0   var_1    var_2   var_3    var_4  ...  var_194  var_195  var_196  var_197  var_198  var_199
0            0  8.9255 -6.7863  11.9081  5.0930  11.4607  ...  18.5227  -2.3978   7.8784   8.5635  12.7803  -1.0914
2            0  8.6093 -2.7457  12.0805  7.8928  10.5825  ...  21.6042   3.1417  -6.5213   8.2675  14.7222   0.3965
4            0  9.8369 -1.4834  12.8746  6.6375  12.2772  ...  13.2876  -1.5121   3.9267   9.5031  17.9974  -8.8104
10           0  5.0702 -0.5447   9.5900  4.2987  12.3910  ...  14.9585  -1.2160   6.6576   9.2553  14.2914  -7.6652
12           0  8.7671 -4.6154   9.7242  7.4242   9.0254  ...  17.2439  -0.0798   5.7389   8.4897  17.0938   4.6106
...        ...     ...     ...      ...     ...      ...  ...      ...      ...      ...      ...      ...      ...
199985       0  9.0249 -3.6379  12.3907  5.1915  12.1701  ...  12.3053   2.5935   8.0172   8.1901  18.5124 -15.6321
199987       0  8.0438 -1.9184  13.1498  9.2027   8.9886  ...  16.9983  -1.5922  -3.5687   8.1765  19.5095 -13.3091
199991       0  9.9909  2.5523  11.9653  6.3958  13.5497  ...  17.0548   0.5328  -5.3444   8.5414  13.2895  -6.7896
199996       0  4.9149 -2.4484  16.7052  6.6345   8.3096  ...  22.2717   1.7337  -2.1651   6.7419  15.9054   0.3388
199998       0  9.7148 -8.6098  13.6104  5.7930  12.5173  ...  20.4158  -0.0786   6.7980  10.0342  15.5289 -13.9001

[103673 rows x 201 columns]

In [13]:
#filter var_6 greater than 5 and var_196 less than 2 
filtered_df=df[(df['var_6']>5) & (df['var_196'] <2)]

In [14]:
#show observations between 20000 and 30000 for 11th column
df.iloc[20000:30001, 10]

20000    6.2325
20001    5.4199
20002    8.5767
20003    6.0312
20004    6.8624
          ...
29996    5.9313
29997    8.9955
29998    7.6509
29999    6.4558
30000    6.3307
Name: var_9, Length: 10001, dtype: float64

In [16]:
#feature correlations(var_0 to var_9) 
features=[f'var_{i}' for i in range(10)] 

#find correlations in features 
corr_matrix=df[features].corr() 

#sort most correlated pairs (excluding self-correlations) 
corr_pairs=corr_matrix.unstack() 
sorted_corr= corr_pairs[corr_pairs.index.get_level_values(0) !=corr_pairs.index.get_level_values(1)] 
sorted_corr=sorted_corr.abs().sort_values(ascending=False) 

#show top 10 most correlated unique pairs 
top_10_corr=sorted_corr.iloc[::2].head(10) 
print(top_10_corr)

var_6  var_0    0.006983
var_0  var_2    0.006573
var_6  var_9    0.005697
var_5  var_9    0.005279
var_0  var_8    0.004962
var_4  var_7    0.004549
var_1  var_8    0.004098
       var_2    0.003980
var_3  var_0    0.003801
var_8  var_3    0.003553
dtype: float64

In [18]:
#remove outliers using Interquartile Range (IQR) method
q1=df.quantile(0.25) 
q3=df.quantile(0.75) 
iqr=q3-q1 

df_no_outliers=df[~((df<(q1-1.5*iqr)) | (df> (q3+1.5*iqr))).any(axis=1)]
df_no_outliers

        target    var_0   var_1    var_2   var_3    var_4  ...  var_194  var_195  var_196  var_197  var_198  var_199
0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  ...  18.5227  -2.3978   7.8784   8.5635  12.7803  -1.0914
2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  ...  21.6042   3.1417  -6.5213   8.2675  14.7222   0.3965
3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  ...  23.0347  -1.2706  -2.9275  10.2922  17.9697  -8.9996
4            0   9.8369 -1.4834  12.8746  6.6375  12.2772  ...  13.2876  -1.5121   3.9267   9.5031  17.9974  -8.8104
5            0  11.4763 -2.3182  12.6080  8.6264  10.9621  ...  14.9452   1.0314  -3.6241   9.7670  12.5809  -4.7602
...        ...      ...     ...      ...     ...      ...  ...      ...      ...      ...      ...      ...      ...
199993       0  13.2152 -5.8006   9.7260  6.5910  12.4612  ...  22.0050   0.3916   6.7302   8.9709  14.5405   6.1149
199994       0  12.3925 -5.8821  11.2323  3.9237  10.4509  ...  14.4656  -1.4843  -3.9299   9.1164  16.3170  -7.5048
199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  ...  18.0249  -1.7939   2.1661   8.5326  16.6660 -17.8661
199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  ...  23.5311  -1.5736   1.2832   8.7155  13.8329   4.1995
199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577  ...  15.2101  -2.4907  -2.2342   8.1857  12.1284   0.1385

[157999 rows x 201 columns]